QE_MaturityApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Home page with the assessment form
    path('QEMaturity/', views.QEMaturity, name='QEMaturity'),
    path('baseline/', views.baseline, name='baseline'),
    path('maturity/', views.maturity, name='maturity'),
    path('maturity_assessment/', views.maturity_assessment, name='maturity_assessment'),

    path('blog1/', views.blog1, name='blog1'),
    path('blog2/', views.blog2, name='blog2'),

]

majorProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("QE_MaturityApp.urls")),
    path('admin/', admin.site.urls)
]

QE_MaturityApp/models.py
from django.db import models

class Assessment(models.Model):
    RESOURCE_TYPES = [
        ('permanent', 'Permanent'),
        ('contractor', 'Contractor'),
    ]
    user = models.CharField(max_length=100)
    resource_type = models.CharField(max_length=10, choices=RESOURCE_TYPES)
    test_cases_executed = models.IntegerField()
    test_execution_days = models.IntegerField()
    resource_count = models.IntegerField()
    manual_tests = models.IntegerField()
    automated_tests = models.IntegerField()
    manual_test_cost = models.DecimalField(max_digits=10, decimal_places=2)
    automated_test_cost = models.DecimalField(max_digits=10, decimal_places=2)
    
    # Adding maturity level questions
    question_1 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_2 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_3 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_4 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_5 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_6 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_7 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_8 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_9 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_10 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_11 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_12 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_13 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)
    question_14 = models.IntegerField(choices=[(0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity')], default=0)

QE_MaturityApp/forms.py
from django import forms
from .models import *


class BaselineForm(forms.Form):
    total_resource_permanent = forms.IntegerField(label='Total Permanent Resources', min_value=0)
    total_resource_contractor = forms.IntegerField(label='Total Contractor Resources', min_value=0)
    total_test_cases = forms.IntegerField(label='Total Test Cases', min_value=0)
    total_execution_time_days = forms.IntegerField(label='Total Execution Time (Days)', min_value=0)

    def clean(self):
        cleaned_data = super().clean()
        total_resource_permanent = cleaned_data.get("total_resource_permanent")
        total_resource_contractor = cleaned_data.get("total_resource_contractor")
        total_test_cases = cleaned_data.get("total_test_cases")
        total_execution_time_days = cleaned_data.get("total_execution_time_days")
        
        # Check if all fields are 0
        if total_resource_permanent == total_resource_contractor == total_test_cases == total_execution_time_days == 0:
            raise forms.ValidationError("Please enter values greater than 0 for at least one field.")
        

class AssessmentForm(forms.Form):
    question_1 = forms.ChoiceField(label="Do you follow an integrated SE/QE development approach?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_2 = forms.ChoiceField(label="Do all Quality Engineers write code for interviews?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_3 = forms.ChoiceField(label="Do you have a Quality Engineering Principles in place (MVE)?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_4 = forms.ChoiceField(label="Do you continue to follow your principles even when you have a tight deadline?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_5 = forms.ChoiceField(label="Are new tests automated from Unit to Release?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_6 = forms.ChoiceField(label="Are E2E tests Embedded as part of your CI/CD?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_7 = forms.ChoiceField(label="Are non-functional test run as part of CI/CD?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_8 = forms.ChoiceField(label="Are all key workflows automated?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_9 = forms.ChoiceField(label="Is your Test Data generation automated?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_10 = forms.ChoiceField(label="Do you have the best tools available to support?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_11 = forms.ChoiceField(label="Are your Environment builds automated?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_12 = forms.ChoiceField(label="Do you monitor Env activity and run synthetic health checks in Env?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_13 = forms.ChoiceField(label="Do you have Automated Test Reporting and MI?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})
    question_14 = forms.ChoiceField(label="Do you have a QE Dashboard that is used by all stakeholders?", choices=((0, 'No Maturity'), (1, 'Low Maturity'), (2, 'Good Maturity'), (3, 'High Maturity/Continuous Maturity')), error_messages={'required': 'Please answer this question.'})

QE_MaturityApp/views.py
from django.shortcuts import render, redirect
from .forms import BaselineForm, AssessmentForm
from .models import Assessment

# This view function renders the home page.
def home(request):
    return render(request, "home.html", {})

# This view function renders the QEMaturity page.
def QEMaturity(request):
    return render(request, "QEMaturity.html", {})

# This view function handles the baseline form submission and calculation.
# It calculates the total cost and cost per test based on the form inputs.
# The results are stored in session variables and passed to the context for rendering.
def baseline(request):
    total_cost = None
    cost_per_test = None
    
    if request.method == 'POST':
        form = BaselineForm(request.POST)
        if form.is_valid():
            total_resource_permanent = form.cleaned_data['total_resource_permanent']
            total_resource_contractor = form.cleaned_data['total_resource_contractor']
            total_test_cases = form.cleaned_data['total_test_cases']
            total_execution_time_days = form.cleaned_data['total_execution_time_days']
            
            if total_resource_permanent == 0 and total_resource_contractor == 0:
                form.add_error(None, 'Total resources cannot be zero.')
            else:
                total_cost = calculate_total_cost(total_resource_permanent, total_resource_contractor, total_test_cases, total_execution_time_days)
                cost_per_test = total_cost / total_test_cases if total_test_cases != 0 else 0

                # Round the results to 2 decimal places
                total_cost = round(total_cost, 2)
                cost_per_test = round(cost_per_test, 2)

                # Store results in session variables
                request.session['total_cost'] = total_cost
                request.session['cost_per_test'] = cost_per_test
                request.session['total_execution_time_days'] = total_execution_time_days  # Store total_execution_time_days in session
        else:
            form.add_error(None, 'All values must be greater than or equal to 0.')
    else:
        form = BaselineForm()

    context = {
        'form': form,
        'total_cost': total_cost,
        'cost_per_test': cost_per_test
    }

    return render(request, 'assessment.html', context)


# This function calculates the total cost based on the provided resources, test cases, and execution time.
# It uses predefined costs for permanent and contractor resources.
def calculate_total_cost(total_resource_permanent, total_resource_contractor, total_test_cases, total_execution_time_days):
    COST_PER_RESOURCE_PERMANENT = 454
    COST_PER_RESOURCE_CONTRACTOR = 1400

    total_cost = (total_resource_permanent * COST_PER_RESOURCE_PERMANENT) + (total_resource_contractor * COST_PER_RESOURCE_CONTRACTOR)
    total_cost *= total_execution_time_days

    return total_cost

# This view function handles the maturity assessment process.
# It takes in the request object as a parameter.
# Depending on the request method (GET or POST), it either renders the assessment form or processes the form data.
def maturity_assessment(request):
    if request.method == 'POST':
        form = AssessmentForm(request.POST)
        if form.is_valid():
            # Process the form data and calculate new scores
            new_total_cost, new_cost_per_test, cost_savings, time_saved, total_maturity_level  = calculate_new_scores(request, form.cleaned_data)  # Switched order of arguments
            # Store results in session variables
            request.session['new_total_cost'] = new_total_cost
            request.session['new_cost_per_test'] = new_cost_per_test
            request.session['new_total_cost'] = new_total_cost
            request.session['new_cost_per_test'] = new_cost_per_test
            request.session['cost_savings'] = cost_savings
            request.session['time_saved'] = time_saved
            # Pass the new scores to the template
                # Pass the new scores and total_maturity_level to the template
            return render(request, 'maturity.html', {
                'new_total_cost': new_total_cost, 
                'new_cost_per_test': new_cost_per_test, 
                'cost_savings': cost_savings, 
                'time_saved': time_saved,
                'total_maturity_level': total_maturity_level
            })
        else:
            print('Form errors:', form.errors)
            return render(request, 'maturity.html', {'form': form})  # Pass the form with errors back to the template
    else:
        form = AssessmentForm()
    return render(request, 'maturity.html', {'form': form})


# This view function handles the calculation of new scores based on the form data.
# It takes in the request object and the form data as parameters.
# The form data is processed and the new scores are calculated and returned.
def calculate_new_scores(request, form_data):
    COST_REDUCTION_PERCENTAGES = {
        range(0, 15): (1.0, "No Maturity"),  # No Maturity = 100% of original cost
        range(15, 29): (0.8, "Low Maturity"),  # Low Maturity = 80% of original cost
        range(29, 39): (0.6, "Good Maturity"),  # Good Maturity = 60% of original cost
        range(39, 61): (0.4, "High Maturity")   # High Maturity/Continuous Maturity = 40% of original cost
    }
    
    # Calculate total maturity level by summing up the answers to all 14 questions
    total_maturity_level = sum(int(form_data.get(f'question_{i}', 0)) for i in range(1, 15))

    # Map the total maturity level to a cost reduction percentage and a maturity level description
    for range_, (percentage, maturity_level) in COST_REDUCTION_PERCENTAGES.items():
        if total_maturity_level in range_:
            cost_reduction_percentage = percentage
            break
    else:
        cost_reduction_percentage = 1.0  # Default to 100% if total_maturity_level is not in any range
        maturity_level = "No Maturity"

    # Assuming original total cost and cost per test are retrieved from session
    original_total_cost = request.session.get('total_cost', 0)
    original_cost_per_test = request.session.get('cost_per_test', 0)

    new_total_cost = round(original_total_cost * cost_reduction_percentage, 2)
    new_cost_per_test = round(original_cost_per_test * cost_reduction_percentage, 2)
    
    # Retrieve the number of test executions from the form data
    num_executions = int(form_data.get('num_executions', 1))

    # Calculate the cost savings and time saved
    cost_savings = (original_total_cost - new_total_cost) * num_executions
    total_execution_time_days = request.session.get('total_execution_time_days', 0)
    time_saved = total_execution_time_days * (1 - cost_reduction_percentage) * num_executions
    
    return new_total_cost, new_cost_per_test, cost_savings, time_saved, maturity_level


def maturity(request):
    return render(request, "maturity.html", {})


def blog1(request):
    return render(request, "blog1.html", {})

def blog2(request):
    return render(request, "blog2.html", {})

QE_MaturityApp/templates/QEMaturity.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page content-->
<div class="jumbotron text-center">
    <h1 class="display-4">Welcome to Your Test Maturity Self Assessment Application</h1>
    <p class="lead">Reduce Cost, Reduce Time and Increase Quality</p>
    <hr class="my-4">
    <p>Learn how to implement modern test practices and calculate detailed costs associated with testing.</p>
    <hr>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Maturity Assessment</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .content-section {
            margin-bottom: 40px;
        }
        .back-button {
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="back-button">
        <a href="#" onclick="history.back()" class="btn btn-secondary">Back</a>
    </div>
    
    <h1>Test Maturity Assessment</h1>

    <div class="content-section">
        <table>
            <thead>
                <tr>
                    <th>Question</th>
                    <th>No Maturity</th>
                    <th>Low Maturity</th>
                    <th>Good Maturity</th>
                    <th>High Maturity/Continuous Maturity</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Do you follow an integrated SE/QE development approach?</td>
                    <td>SE & QE Not aligned</td>
                    <td>Low SE/QE collaboration</td>
                    <td>High SE & QE collaboration</td>
                    <td>Integrated Dev/QA teams</td>
                </tr>
                <tr>
                    <td>Do all Quality Engineers write code for interviews?</td>
                    <td>No code written and coding not considered part of interview</td>
                    <td>Coding skills considered as part of interview</td>
                    <td>Coding skills evidence key as part of interview</td>
                    <td>Code written in interviews or clear evidence of coding skills provided</td>
                </tr>
                <tr>
                    <td>Do your Quality Engineers have training opportunities and budget?</td>
                    <td>No opportunities or budget</td>
                    <td>Time & budget made available on request</td>
                    <td>Time and Budget available</td>
                    <td>Team has time and budget with clear skills matrix, whilst also having time to experiment and learn new things</td>
                </tr>
                <tr>
                    <td>Do you have Quality Engineering Principles in place (MVE)?</td>
                    <td>No QE/MVE principles in place</td>
                    <td>Legacy QE principles in place</td>
                    <td>QE principles in place that reflect modern engineering</td>
                    <td>Mature QE principles in place and constantly reviewed/adjusted where necessary</td>
                </tr>
                <tr>
                    <td>Do you continue to follow your principles even when you have a tight deadline?</td>
                    <td>Principles not followed if deadlines are tight</td>
                    <td>Some principles dropped if deadlines are tight</td>
                    <td>Based on risk we may veer away from low risk principles</td>
                    <td>We stick to our principles always</td>
                </tr>
                <tr>
                    <td>Are new tests automated from Unit to Release?</td>
                    <td>No tests automated</td>
                    <td>Some (Unit/component etc)</td>
                    <td>Most with some gaps (e.g. NFT)</td>
                    <td>All tests are automated with reuse across test types</td>
                </tr>
                <tr>
                    <td>Are E2E tests embedded as part of your CI/CD?</td>
                    <td>No E2E test embedded in CI/CD</td>
                    <td>Automation in place for most E2E tests but not integrated in CI/CD</td>
                    <td>Some E2E tests automated and embedded in CI/CD</td>
                    <td>All E2E tests integrated as part of CI/CD – reuse of test assets of high importance</td>
                </tr>
                <tr>
                    <td>Are non-functional tests run as part of CI/CD?</td>
                    <td>No NFT run as part of CI/CD</td>
                    <td>Automation in place for most NFTs but not integrated in CI/CD</td>
                    <td>Some NFTs automated and embedded in CI/CD</td>
                    <td>All NFTs integrated as part of CI/CD – reuse of test assets of high importance</td>
                </tr>
                <tr>
                    <td>Are all key workflows automated?</td>
                    <td>No key workflows automated</td>
                    <td>Some key workflows automated</td>
                    <td>High level of key workflows automated</td>
                    <td>All key workflows automated</td>
                </tr>
                <tr>
                    <td>Is your test data generation automated?</td>
                    <td>No test data generation automated</td>
                    <td>Majority generated manually but some automation in place</td>
                    <td>High levels of automated test data generation</td>
                    <td>All test data generated through automation</td>
                </tr>
                <tr>
                    <td>Do you have the best tools available to support?</td>
                    <td>Best tools not available</td>
                    <td>Some tools in place with no retro/review process across wider group tool usage</td>
                    <td>Good tools in place</td>
                    <td>Modern tools available for POC and usage quickly and efficiently</td>
                </tr>
                <tr>
                    <td>Are your environment builds automated?</td>
                    <td>No env automation</td>
                    <td>Some env automation (e.g. platform container deployments automated)</td>
                    <td>High levels of env build automation with exceptions</td>
                    <td>All env builds are automated</td>
                </tr>
                <tr>
                    <td>Do you monitor environment activity and run synthetic health checks in environment?</td>
                    <td>No env health checks</td>
                    <td>Manual health checks in place</td>
                    <td>Automated health checks in place across most environments</td>
                    <td>Automated real-time environment health checks in place across all environments</td>
                </tr>
                <tr>
                    <td>Do you have automated test reporting and MI?</td>
                    <td>No automated reporting or MI</td>
                    <td>Some automated MI in place but a lot of manual work required</td>
                    <td>Automated reporting in place and run ad-hoc where required</td>
                    <td>Real-time test reporting and MI in place across all tests</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

{% endblock %}

QE_MaturityApp/templates/assessment.html
{% extends 'base.html' %}

{% block content %}

<!-- Page content-->
<div class="jumbotron text-center">
    <h1 class="display-4">Welcome to Your Test Maturity Self Assessment Application</h1>
    <p class="lead">Reduce Cost, Reduce Time and Increase Quality</p>
    <hr class="my-4">
    <p>Learn how to implement modern test practices and calculate detailed costs associated with testing.</p>

    <!-- Line break -->
    <hr>


<div class="container mt-4">
    <h1 class="text-center">Baseline Assessment</h1>

    <form method="post" action="{% url 'baseline' %}" class="mx-auto" style="max-width: 600px;">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group row">
            <label for="id_total_resource_permanent" class="col-sm-6 col-form-label">Total Permanent Resources:</label>
            <div class="col-sm-6">
                {{ form.total_resource_permanent }}
                {% if form.total_resource_permanent.errors %}
                    <div class="error">{{ form.total_resource_permanent.errors }}</div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row">
            <label for="id_total_resource_contractor" class="col-sm-6 col-form-label">Total Contractor Resources:</label>
            <div class="col-sm-6">
                {{ form.total_resource_contractor }}
                {% if form.total_resource_contractor.errors %}
                    <div class="error">{{ form.total_resource_contractor.errors }}</div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row">
            <label for="id_total_test_cases" class="col-sm-6 col-form-label">Total Test Cases:</label>
            <div class="col-sm-6">
                {{ form.total_test_cases }}
                {% if form.total_test_cases.errors %}
                    <div class="error">{{ form.total_test_cases.errors }}</div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row">
            <label for="id_total_execution_time_days" class="col-sm-6 col-form-label">Total Execution Time (Days):</label>
            <div class="col-sm-6">
                {{ form.total_execution_time_days }}
                {% if form.total_execution_time_days.errors %}
                    <div class="error">{{ form.total_execution_time_days.errors }}</div>
                {% endif %}
            </div>
        </div>

        <div class="text-center">
            <input type="submit" value="Submit" class="btn btn-secondary">
        </div>
    </form>

    {% if total_cost is not None %}
        <h2 class="text-center mt-5">Results</h2>
        <div class="d-flex justify-content-center">
            <div class="card bg-light mb-3 mx-2" style="width: 18rem;">
                <div class="card-header">Total Cost</div>
                <div class="card-body">
                    <h5 class="card-title">£{{ total_cost }}</h5>
                </div>
            </div>
            <div class="card bg-light mb-3 mx-2" style="width: 18rem;">
                <div class="card-header">Cost Per Test</div>
                <div class="card-body">
                    <h5 class="card-title">£{{ cost_per_test }}</h5>
                </div>
            </div>
        </div>

        <div class="text-center mt-3">
            <a href="{% url 'maturity' %}" class="btn btn-secondary">Maturity Assessment</a>
        </div>
    {% endif %}
</div>



{% endblock %}

QE_MaturityApp/templates/base.html
<!-- This is the base template that all other templates will inherit from -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Test Maturity Self Assessment</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    
    </head>
    <body>
        {% include 'navbar.html' %}

        {% block content %}
        <!-- This is where the content of child templates will be inserted -->
        {% endblock %}

        <!-- footer and scripts -->
            <!-- Line break -->
    <hr>
        <footer>
            <p>Copyright &copy; 2024 Ben Pavey - Digital & Technology - Software Engineer - Major Project</p>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

QE_MaturityApp/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page content-->
<div class="jumbotron text-center">
    <h1 class="display-4">Welcome to Your Test Maturity Self Assessment Application TEST</h1>
    <p class="lead">Reduce Cost, Reduce Time and Increase  Quality</p>
    <hr class="my-4">
    <p>Learn how to implement modern test practices and calculate detailed costs associated with testing.</p>

    <!-- Line break -->
    <hr>


<!-- Card Sections -->
<section class="card-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Calculator</h5>
              <p class="card-text">Discover the currency cost associated with quality, and how maturing engineering practice can reduce the cost. Use this as a tool to demostrate value to your stakeholders</p>
              <a href="{% url 'baseline' %}" class="btn btn-secondary">Learn More</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Knowledge Articles</h5>
              <p class="card-text">Test Guides, best practices, advice and training material to support you to mature your Quality Engineer practice</p>
              <a href="{% url 'blog1' %}" class="btn btn-secondary">Learn More</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Test Automation Frameworks</h5>
              <p class="card-text">Discover more about test automation tooling and complete frameworks to automate your manual testing. Grab a coffee whilst your automation does the heavy lifting!</p>
              <a href="{% url 'blog2' %}" class="btn btn-secondary">Learn More</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Modal -->
<div class="modal fade" id="sectionOneModal" tabindex="-1" aria-labelledby="sectionOneModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="sectionOneModalLabel">Detailed Content for Section One</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Insert detailed content here -->
          <p>This is where you can add more detailed information about Section One.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  

</div>


  
{% endblock %}